apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.flaskapp.name }}
  name: todo-flaskapp
spec:
  ports:
    - name: "http"
      port: {{ .Values.flaskapp.service.port }}
      targetPort: {{ .Values.flaskapp.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: {{ .Values.flaskapp.name }}
  type: {{ .Values.flaskapp.service.type }}
status:
  loadBalancer: {}
