apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    name: flask-app
    app: flask-app
spec:
  selector:
    name: flask-app
  ports:
   - port: 5000
     name: http
     targetPort: 5000
     protocol: TCP