nameoverride: ""

mongo:
  name: mongo
  image:
    registry: docker.io
    repository: mvertes/alpine-mongo
    tag: latest
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017

flaskapp:
  name: todo-flaskapp
  env: production
  image:
    registry: docker.io
    repository: coolboi567/todo-flaskapp
    tag: latest
  imagePullPolicy: Always
  service:
    type: ClusterIP
    port: 5000